# Generated by Django 3.0 on 2020-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=32)),
                ('course_duration', models.IntegerField()),
                ('course_fee', models.IntegerField()),
                ('course_start_date', models.DateField()),
                ('course_start_time', models.TimeField()),
                ('course_trainer_name', models.CharField(max_length=32)),
                ('course_trainer_exp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminLoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('phone', models.IntegerField()),
                ('courses', models.CharField(max_length=32)),
                ('shifts', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=6)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
