# Generated by Django 3.0 on 2020-04-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ADVANCED_LEARNING_INSTITUTE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='time_date',
            field=models.DateField(),
        ),
    ]
