# Generated by Django 3.0 on 2020-04-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ADVANCED_LEARNING_INSTITUTE', '0002_feedbackmodel_time_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='time_date',
            new_name='feedback_date',
        ),
    ]
